name: Publish NuGet
on:
  release:
    types: [ published ]
jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore, Build, Pack
      working-directory: DataForge.Core
      run: |
        dotnet restore DataForge.Core.sln
        dotnet build --configuration Release --no-restore
        dotnet pack --configuration Release --no-build --output nupkg/
    - name: Push
      working-directory: DataForge.Core
      run: dotnet nuget push nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
